name: React

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: frontend
        
    strategy:
      max-parallel: 4
      matrix:
        node-version: [12.16.3]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - run: npm run test
      env:
        CI: true
